postgres-operator:
  image:
    registry: zalando-remote.binary.alfabank.ru
    repository: acid/postgres-operator
    pullPolicy: "IfNotPresent"
  configLogicalBackup:
    logical_backup_docker_image: "docker.io/logical-backup:v1.10.1"
    # prefix for the backup job name
    logical_backup_job_prefix: "logical-backup-"
    # storage provider - either "s3", "gcs" or "az"
    logical_backup_provider: "s3"
    # S3 Access Key ID
    logical_backup_s3_access_key_id: ""
    # S3 bucket to store backup results
    logical_backup_s3_bucket: "my-bucket-url"
    # S3 region of bucket
    logical_backup_s3_region: ""
    # S3 endpoint url when not using AWS
    logical_backup_s3_endpoint: ""
    # S3 Secret Access Key
    logical_backup_s3_secret_access_key: ""
    # S3 server side encryption
    logical_backup_s3_sse: "AES256"
    # S3 retention time for stored backups for example "2 week" or "7 days"
    logical_backup_s3_retention_time: ""
    # backup schedule in the cron format
    logical_backup_schedule: "30 00 * * *"
  configConnectionPooler:
    connection_pooler_image: "docker.io/pgbouncer:master-27"
  configGeneral:
    docker_image: docker.io/zalando/spilo-15:3.0-p1
  resources:
    limits:
      cpu: 500m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 250Mi
  affinity: {}
  nodeSelector: {}
  tolerations: []

postgres-operator-ui:
  image:
    registry: docker.io
    repository: postgres-operator-ui
    tag: v1.10.1
    pullPolicy: "IfNotPresent"
  envs:
    appUrl: "http://localhost:8081"
    operatorApiUrl: "http://postgres-operators:8080"
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 100m
      memory: 100Mi
  ingress:
    enabled: true
    ingressClassName: "nginx"
    hosts:
      - host: localhost
        paths: ["/"]