apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook3
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook3
    server: {{ .Values.spec.destination.server }}
  project: sians-test
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: helm-guestbook
    helm:
      valueFiles:
        - ../values/values3.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true