apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zolando
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: postgres-operator
    server: {{ .Values.spec.destination.server }}
  project: sians-test
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    path: postgres-operators
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true