apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook4
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: helm-guestbook4
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL:  https://github.com/pyroman30/job2
    targetRevision: HEAD
    path: helm-guestbook
    helm:
      valueFiles:
        - ../values/values4.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true