pg-operator:
  replicaCount: 1

  operatorImageRepository: percona/percona-postgresql-operator
  imagePullPolicy: IfNotPresent
  image: ""
  watchAllNamespaces: true
  resources:
    limits:
      cpu: 200m
      memory: 500Mi
    requests:
      cpu: 100m
      memory: 20Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}

  # disableTelemetry: according to
  # https://docs.percona.com/percona-operator-for-postgresql/2.0/telemetry.html
  # this is how you can disable telemetry collection
  # default is false which means telemetry will be collected
  disableTelemetry: false
  operatorDebug: false
