{{ if or (not (hasKey $.Values.fs_datamart_backend "enabled")) (eq (coalesce $.Values.fs_datamart_backend.enabled false) true) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fs-datamart-backend
spec:
  hosts:
    - {{ .Values.fs_datamart_backend.virtualService.web.host }}
  gateways:
  - istio-ingress/mdp-gateway
  http:
  - match:
    - uri:
        prefix: {{ .Values.fs_datamart_backend.virtualService.web.path }}
    route:
    - destination:
        port:
          number: {{ .Values.fs_datamart_backend.virtualService.web.port }}
        host: fs-datamart-backend
{{- end }}

